# Configuración mínima de AIDE para la práctica
# Se limita a vigilar los dos elementos exigidos en el ejercicio:
# /etc/passwd y /usr/bin/backdoor

database_in=file:/var/lib/aide/aide-practica.db
database_out=file:/var/lib/aide/aide-practica.db.new
gzip_dbout=no

/etc/passwd p+i+n+u+g+s+m+c+sha256
/usr/bin/backdoor p+i+n+u+g+s+m+c+sha256
